### ISSUE TITLE
When Question Generation Issues

### ISSUE THREAD

**Issue by raymond-yang** [liangeric/nlpQ-A#12]
@meliyang outlined  general logic for naively parsing when questions.

1. Look for sentences that have date, 
    a. done with Spacy NER looking for entity type DATE
2. Identify the subject[s], and their immediately "root" or "head" verb. 
    a. Looped through all of the noun chunks looking for one that has .dep_ of nsubj and then adding its root.
3. Identify the object that corresponds to the verb above
4. Collect into a question of the format "When [auxVerb: was/did] nsubj infinitive Verb object"

Some samples of current implementations
![image](https://user-images.githubusercontent.com/46874298/98459271-697bc800-2167-11eb-9a4f-0c2e1c840031.png)

![image](https://user-images.githubusercontent.com/46874298/98459321-d55e3080-2167-11eb-9197-871296a1ae48.png)

- [x] Need to change the parsed verb to infinitive, done with spacy built lemmatizer.
- [x] Need to choose the auxVerb, picking between "to do" or "to be"
- [x] Some question only make sense when we include some preposition. But need to pick the right one
- [x] Long complex sentences have multiple subjects and verbs and objects, unsure what to do in that case.

**Comment by meliyang** [comment]
fixed by looking at the "when phrase"'s verb that it points to and looping through its children
