### ISSUE TITLE
BERT picking up pronouns/subjects

### ISSUE THREAD

**Issue by liangeric** [liangeric/nlpQ-A#8]
Seems like BERT doesn't perform too well when the answer is the first answer, could be linked to the BERT Date Error issue, but maybe move subject to the back end of the sentence. For example if the question is "Who perfected the art of carving intricate relief decoration?" and the answer is "They perfected the art of carving intricate relief decoration." it will not find they, however the sentence "Perfected the art of carving intricate relief decoration was them." finds "them" as the correct answer. I suspect it has to do with looking for the verb "was" in the sentence.

**Comment by meliyang** [comment]
@liangeric fixed this with a bigger and better BERT model 😄
